"""empty message

Revision ID: e1d572336c0
Revises: None
Create Date: 2017-02-20 14:43:25.880000

"""

# revision identifiers, used by Alembic.
revision = 'e1d572336c0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interest')
    op.drop_table('loans')
    op.drop_table('customers')
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('can_create', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('can_update', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('can_delete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('customers',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('number_shares', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('mobile_phone', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('is_dormant', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('loans',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('interest', mysql.FLOAT(), nullable=True),
    sa.Column('payment', mysql.FLOAT(), nullable=True),
    sa.Column('total_payable', mysql.FLOAT(), nullable=True),
    sa.Column('total_payment', mysql.FLOAT(), nullable=True),
    sa.Column('outstanding_balance', mysql.FLOAT(), nullable=True),
    sa.Column('fully_paid_on', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('date_release', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('date_due', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('is_dormant', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], [u'customers.id'], name=u'loans_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('interest',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
